// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Data/models/object_box_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 427336182165892068),
      name: 'WeatherModelObjectBox',
      lastPropertyId: const IdUid(9, 5406310281028677344),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2230692901203195184),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5573760367898116819),
            name: 'tempC1',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4181741539906067762),
            name: 'tempC2',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 532111584920823921),
            name: 'tempC3',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 5406310281028677344),
            name: 'theme',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 427336182165892068),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [64066134282165742],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        4784581672183369026,
        2744800474288260779,
        8625939283706865546,
        132076974877930364,
        2716626961604356253,
        6887995002721336377,
        8621501264502193062,
        4329368223931562233,
        6477151710208542996,
        4706446122322395198,
        4132311396880457956,
        2099251978588087948,
        4251566893806913185,
        3317499356602479563,
        8287564820073328455,
        7955823399980311421,
        8400700868489427036,
        4276075180856658761,
        1400278501694472358,
        8761142226747617627
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    WeatherModelObjectBox: EntityDefinition<WeatherModelObjectBox>(
        model: _entities[0],
        toOneRelations: (WeatherModelObjectBox object) => [],
        toManyRelations: (WeatherModelObjectBox object) => {},
        getId: (WeatherModelObjectBox object) => object.id,
        setId: (WeatherModelObjectBox object, int id) {
          object.id = id;
        },
        objectToFB: (WeatherModelObjectBox object, fb.Builder fbb) {
          final themeOffset = fbb.writeString(object.theme);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.tempC1);
          fbb.addInt64(2, object.tempC2);
          fbb.addInt64(3, object.tempC3);
          fbb.addOffset(8, themeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = WeatherModelObjectBox(
              tempC1:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              tempC2:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              tempC3:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              theme: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 20, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [WeatherModelObjectBox] entity fields to define ObjectBox queries.
class WeatherModelObjectBox_ {
  /// see [WeatherModelObjectBox.id]
  static final id =
      QueryIntegerProperty<WeatherModelObjectBox>(_entities[0].properties[0]);

  /// see [WeatherModelObjectBox.tempC1]
  static final tempC1 =
      QueryIntegerProperty<WeatherModelObjectBox>(_entities[0].properties[1]);

  /// see [WeatherModelObjectBox.tempC2]
  static final tempC2 =
      QueryIntegerProperty<WeatherModelObjectBox>(_entities[0].properties[2]);

  /// see [WeatherModelObjectBox.tempC3]
  static final tempC3 =
      QueryIntegerProperty<WeatherModelObjectBox>(_entities[0].properties[3]);

  /// see [WeatherModelObjectBox.theme]
  static final theme =
      QueryStringProperty<WeatherModelObjectBox>(_entities[0].properties[4]);
}
